name: 'Link check'

on:
  schedule:
    # check links at 01:30 a.m. every day
    - cron: '30 1 * * *'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: linkchecker
        run: |
          pip install linkchecker
          linkchecker https://opencompass.readthedocs.io/ --no-robots -t 30
